fix(UpdateData): large description causes crash when tapping download
Fixes #275:
```
IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
```