fix(main): maybe fix `IllegalArgumentException` empty backstack crash
Extremely rare crash seen only <10 times. Exact cause is unknown. It's
possible that protecting navigation events with `dropUnlessResumed` is
enough, as shown in https://github.com/android/nav3-recipes/issues/102.
Exception message:
> IllegalArgumentException: NavDisplay backstack cannot be empty